# Generated by Django 5.2.4 on 2025-11-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamedays', '0021_gameday_address')
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueRuleset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "league_points",
                    models.DecimalField(decimal_places=2, default=2, max_digits=4),
                ),
                (
                    "draw_points",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                (
                    "loss_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "points_win_same_league",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "points_win_other_league",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "points_draw_same_league",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "points_draw_other_league",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "max_points_same_league",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "max_points_other_league",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TieBreakStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("points", "Siegpunkte"),
                            ("league_quotient", "Ligaquotient"),
                            ("direct_wins", "Direkte Siegpunkte"),
                            ("direct_point_diff", "Direkte Punktedifferenz"),
                            ("direct_points_scored", "Direkt erzielte Punkte"),
                            ("overall_point_diff", "Gesamte Punktedifferenz"),
                            ("overall_points_scored", "Gesamt erzielte Punkte"),
                            ("name_ascending", "Teamname (A–>Z)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalTeamLeaguePoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum_points", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gamedays.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeagueGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups_league",
                        to="gamedays.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups_season",
                        to="gamedays.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeagueSeasonConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addition_team_points",
                    models.ManyToManyField(
                        through="league_table.AdditionalTeamLeaguePoints",
                        to="gamedays.team",
                    ),
                ),
                (
                    "exclude_gamedays",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_in_configs",
                        to="gamedays.gameday",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_league",
                        to="gamedays.league",
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="league_table.leagueruleset",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_season",
                        to="gamedays.season",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="additionalteamleaguepoints",
            name="league_season_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="league_table.leagueseasonconfig",
            ),
        ),
        migrations.CreateModel(
            name="LeagueRulesetTieBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league_table.leagueruleset",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league_table.tiebreakstep",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("ruleset", "step")},
            },
        ),
        migrations.AddField(
            model_name="leagueruleset",
            name="tie_break_steps",
            field=models.ManyToManyField(
                related_name="rulesets",
                through="league_table.LeagueRulesetTieBreak",
                to="league_table.tiebreakstep",
            ),
        ),
    ]
