# Generated by Django 5.2 on 2025-11-14 22:00
from django.db import migrations


def create_tiebreak_steps_and_defaults(apps, schema_editor):
    TieBreakStep = apps.get_model("league_table", "TieBreakStep")
    LeagueRuleset = apps.get_model("league_table", "LeagueRuleset")
    LeagueRulesetTieBreak = apps.get_model("league_table", "LeagueRulesetTieBreak")

    # Define the steps
    tiebreak_steps = [
        ("win_points", "Siegpunkte"),
        ("direct_wins", "Direkte Siege"),
        ("direct_point_diff", "Direkte Punktedifferenz"),
        ("direct_points_scored", "Direkt erzielte Punkte"),
        ("overall_point_diff", "Gesamte Punktedifferenz"),
        ("overall_points_scored", "Gesamt erzielte Punkte"),
        ("name_ascending", "Teamname"),
    ]

    # Create the TieBreakStep entries
    for key, label in tiebreak_steps:
        TieBreakStep.objects.get_or_create(key=key, label=label)

    # Fetch the rulesets or create them if they don't exist
    standard_ruleset, _ = LeagueRuleset.objects.get_or_create(name="Standard Flag Tie Break Regeln")
    dffl_ruleset, _ = LeagueRuleset.objects.get_or_create(
        name="DFFL Liga Regeln",
        defaults={
            "points_win_same_league": 1,
            "points_win_other_league": 2,
            "points_draw_same_league": 0.5,
            "points_draw_other_league": 1,
            "max_points_same_league": 1,
            "max_points_other_league": 2,
        }
    )

    # Default order for Standard Flag Tie Break Regeln
    standard_orders = [
        ("win_points", 1, "descending"),
        ("direct_wins", 5, "descending"),
        ("direct_point_diff", 10, "descending"),
        ("direct_points_scored", 15, "descending"),
        ("overall_point_diff", 20, "descending"),
        ("overall_points_scored", 25, "descending"),
        ("name_ascending", 30, "ascending"),
    ]

    for key, order, sort_order in standard_orders:
        step = TieBreakStep.objects.get(key=key)
        LeagueRulesetTieBreak.objects.get_or_create(
            ruleset=standard_ruleset, step=step, defaults={"order": order, "sort_order": sort_order}
        )

    # Default order for DFFL Liga Regeln
    # Same as standard, but adjust Siegpunkte order to 5, then others incremented
    dffl_orders = [
        ("win_points", 5, "descending"),
        ("direct_wins", 10, "descending"),
        ("direct_point_diff", 15, "descending"),
        ("direct_points_scored", 20, "descending"),
        ("overall_point_diff", 25, "descending"),
        ("overall_points_scored", 30, "descending"),
        ("name_ascending", 35, "ascending"),
    ]

    for key, order, sort_order in dffl_orders:
        step = TieBreakStep.objects.get(key=key)
        LeagueRulesetTieBreak.objects.get_or_create(
            ruleset=dffl_ruleset, step=step, defaults={"order": order, "sort_order": sort_order}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("league_table", "0001_initial"),  # adjust to your last migration
    ]

    operations = [
        migrations.RunPython(create_tiebreak_steps_and_defaults),
    ]
