# Generated by Django 5.2.4 on 2025-11-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_table", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalteamleaguepoints",
            name="tie_step_for_sum_points",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_table.tiebreakstep",
            ),
            preserve_default=False,
        ),
    ]
