# Generated by Django 5.2.4 on 2025-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0027_alter_league_name_alter_season_name"),
        ("league_table", "0003_additionalteamleaguepoints_tie_step_for_sum_points"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdditionalTeamLeaguePoints",
            new_name="TeamPointAdjustments",
        ),
        migrations.RemoveField(
            model_name="leagueseasonconfig",
            name="addition_team_points",
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="team_point_adjustments",
            field=models.ManyToManyField(
                through="league_table.TeamPointAdjustments", to="gamedays.team"
            ),
        ),
    ]
