# Generated by Django 5.2.4 on 2025-11-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0027_alter_league_name_alter_season_name"),
        (
            "league_table",
            "0004_rename_additionalteamleaguepoints_teampointadjustments_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueruleset",
            name="exclude_main_league_for_league_points",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excluded_league",
                to="gamedays.league",
            ),
        ),
        migrations.AlterField(
            model_name="tiebreakstep",
            name="key",
            field=models.CharField(
                choices=[
                    ("win_points", "Siegpunkte"),
                    ("league_points", "Ligapunkte"),
                    ("direct_wins", "Direkte Siegpunkte"),
                    ("direct_point_diff", "Direkte Punktedifferenz"),
                    ("direct_points_scored", "Direkt erzielte Punkte"),
                    ("overall_point_diff", "Gesamte Punktedifferenz"),
                    ("overall_points_scored", "Gesamt erzielte Punkte"),
                    ("name_ascending", "Teamname (A–>Z)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
