# Generated by Django 5.2.4 on 2025-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "league_table",
            "0005_leagueruleset_exclude_main_league_for_league_points_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguerulesettiebreak",
            name="sort_order",
            field=models.CharField(
                choices=[("ascending", "Aufsteigend"), ("descending", "Absteigend")],
                default="descending",
                max_length=50,
            ),
        ),
    ]
