# Generated by Django 5.2.4 on 2025-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_table", "0006_leaguerulesettiebreak_sort_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leagueruleset",
            name="draw_points",
        ),
        migrations.RemoveField(
            model_name="leagueruleset",
            name="league_points",
        ),
        migrations.RemoveField(
            model_name="leagueruleset",
            name="loss_points",
        ),
        migrations.AddField(
            model_name="leagueruleset",
            name="league_quotient_precision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="leagueruleset",
            name="points_loss_other_league",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="leagueruleset",
            name="points_loss_same_league",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="leagueruleset",
            name="max_points_other_league",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="leagueruleset",
            name="max_points_same_league",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="leagueruleset",
            name="points_draw_other_league",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name="leagueruleset",
            name="points_draw_same_league",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name="leagueruleset",
            name="points_win_other_league",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="leagueruleset",
            name="points_win_same_league",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="tiebreakstep",
            name="key",
            field=models.CharField(
                choices=[
                    ("league_quotient", "Ligaquotient"),
                    ("direct_wins", "Direkte Siegpunkte"),
                    ("direct_point_diff", "Direkte Punktedifferenz"),
                    ("direct_points_scored", "Direkt erzielte Punkte"),
                    ("overall_point_diff", "Gesamte Punktedifferenz"),
                    ("overall_points_scored", "Gesamt erzielte Punkte"),
                    ("name_ascending", "Teamname (A–>Z)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
