# Generated by Django 5.2.4 on 2025-11-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league_table", "0007_remove_leagueruleset_draw_points_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leagueruleset",
            old_name="exclude_main_league_for_league_points",
            new_name="leagues_for_league_points",
        ),
    ]
