# Generated by Django 5.2.4 on 2025-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0027_alter_league_name_alter_season_name"),
        (
            "league_table",
            "0008_rename_exclude_main_league_for_league_points_leagueruleset_leagues_for_league_points",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leagueruleset",
            name="leagues_for_league_points",
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="leagues_for_league_points",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="gamedays.league"
            ),
        ),
    ]
