# Generated by Django 5.2.4 on 2025-11-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "league_table",
            "0009_remove_leagueruleset_leagues_for_league_points_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiebreakstep",
            name="key",
            field=models.CharField(
                choices=[
                    ("league_quotient", "Ligaquotient"),
                    ("league_points", "Siegpunkte"),
                    ("direct_wins", "Direkte Siegpunkte"),
                    ("direct_point_diff", "Direkte Punktedifferenz"),
                    ("direct_points_scored", "Direkt erzielte Punkte"),
                    ("overall_point_diff", "Gesamte Punktedifferenz"),
                    ("overall_points_scored", "Gesamt erzielte Punkte"),
                    ("name_ascending", "Teamname (A–>Z)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
