# Generated by Django 5.2.4 on 2025-12-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0028_remove_seasonleagueteam_team_seasonleagueteam_teams"),
        ("league_table", "0011_create_tie_break_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueseasonconfig",
            name="leagues_for_league_points",
            field=models.ManyToManyField(
                blank=True, default=None, to="gamedays.league"
            ),
        ),
    ]
