# Generated by Django 5.2.4 on 2026-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_table", "0012_alter_leagueseasonconfig_leagues_for_league_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="group_by_leagues",
            field=models.BooleanField(default=False),
        ),
    ]
