# Generated by Django 5.2.4 on 2026-03-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0028_remove_seasonleagueteam_team_seasonleagueteam_teams"),
        ("league_table", "0013_leagueseasonconfig_group_by_leagues"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="allow_officials_to_register",
            field=models.BooleanField(
                default=False,
                help_text="Die nachfolgenden Felder funktionieren nur, wenn dieses gecheckt ist",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="officials_per_gameday_number",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Dieses Feld verliert gegenüber dem vorherigen Feld",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="officials_per_gameday_per_field",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Dieses Feld gewinnt gegenüber dem nachfolgenden Feld",
            ),
        ),
        migrations.AlterField(
            model_name="tiebreakstep",
            name="key",
            field=models.CharField(
                choices=[
                    ("win_quotient", "Ligaquotient"),
                    ("win_points", "Siegpunkte"),
                    ("direct_wins", "Direkte Siegpunkte"),
                    ("direct_point_diff", "Direkte Punktedifferenz"),
                    ("direct_points_scored", "Direkt erzielte Punkte"),
                    ("overall_point_diff", "Gesamte Punktedifferenz"),
                    ("overall_points_scored", "Gesamt erzielte Punkte"),
                    ("name_ascending", "Teamname (A–>Z)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="OverrideOfficialGamedaySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_officials_to_register",
                    models.BooleanField(
                        default=False,
                        help_text="Die nachfolgenden Felder funktionieren nur, wenn dieses gecheckt ist",
                    ),
                ),
                (
                    "officials_per_gameday_per_field",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Dieses Feld gewinnt gegenüber dem nachfolgenden Feld",
                    ),
                ),
                (
                    "officials_per_gameday_number",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Dieses Feld verliert gegenüber dem vorherigen Feld",
                    ),
                ),
                (
                    "gameday",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_override",
                        to="gamedays.gameday",
                    ),
                ),
                (
                    "league_season_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league_table.leagueseasonconfig",
                    ),
                ),
            ],
        ),
    ]
