# Generated by Django 5.2.4 on 2026-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_table", "0013_leagueseasonconfig_group_by_leagues"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueruleset",
            name="allow_official_registration",
            field=models.BooleanField(default=False),
        ),
    ]
