#!/bin/bash

set -e

show_help() {
    echo "Usage: $0 [-b <branch>] [-r <remote>] [--pr-remote <remote>] [major|minor|patch|stage|demo]"
    echo
    echo "Flags:"
    echo "  -b, --branch <branch>        Deploy from specified branch via worktree"
    echo "  -r, --remote <remote>        Push release branch to this remote (default: origin)"
    echo "  --pr-remote <remote>         Create PR against this remote (default: upstream)"
    echo "  -h, --help                   Show this help message and exit"
    echo
    echo "Options:"
    echo "  major     Bump the major version (production)"
    echo "  minor     Bump the minor version (production)"
    echo "  patch     Bump the patch version (production)"
    echo "  stage     Create/increment staging RC version"
    echo "  demo      Create/increment demo version"
    echo
    echo "Workflow:"
    echo "  1. Deploy from origin branch (or specified via -b)"
    echo "  2. Push release branch to origin (or specified via -r)"
    echo "  3. Create PR to upstream (or specified via --pr-remote)"
    echo "  4. Merge PR in upstream repository"
    echo "  5. Sync upstream back to origin"
    echo
    echo "Examples:"
    echo "  $0 stage                                    # Current branch → origin, PR to upstream"
    echo "  $0 -b origin/master patch                  # origin/master → origin, PR to upstream"
    echo "  $0 -b upstream/master -r origin stage      # upstream/master → origin, PR to upstream"
    echo "  $0 -r upstream -pr-remote upstream patch   # Current → upstream, PR to upstream"
}

# Validate that a branch exists
validate_branch() {
    local branch="$1"

    # Check if it's a local branch
    if git show-ref --verify --quiet "refs/heads/$branch"; then
        return 0
    fi

    # Check if it's a remote-tracking branch
    if git show-ref --verify --quiet "refs/remotes/$branch"; then
        return 0
    fi

    # Try to parse as remote/branch format and fetch
    if [[ "$branch" =~ ^([^/]+)/(.+)$ ]]; then
        local remote="${BASH_REMATCH[1]}"
        local branch_name="${BASH_REMATCH[2]}"

        echo "Fetching from remote '$remote'..."
        if git fetch "$remote" 2>/dev/null; then
            # Check again after fetch
            if git show-ref --verify --quiet "refs/remotes/$branch"; then
                return 0
            fi
        fi
    fi

    echo "Error: Branch '$branch' not found"
    echo "Checked:"
    echo "  - Local branch: refs/heads/$branch"
    echo "  - Remote-tracking branch: refs/remotes/$branch"
    exit 1
}

# Create a temporary worktree
create_worktree() {
    local branch="$1"
    local timestamp=$(date +%Y%m%d-%H%M%S)
    local random=$(head -c 4 /dev/urandom | xxd -p)
    local worktree_path="/tmp/leaguesphere-deploy-${timestamp}-${random}"

    echo "Creating worktree at: $worktree_path" >&2
    echo "From branch: $branch" >&2

    if ! git worktree add "$worktree_path" "$branch" >&2; then
        echo "Error: Failed to create worktree" >&2
        exit 1
    fi

    echo "$worktree_path"
}

# Cleanup worktree
cleanup_worktree() {
    local worktree_path="$1"

    if [ -z "$worktree_path" ]; then
        return 0
    fi

    echo "Cleaning up worktree: $worktree_path" >&2

    # Try to remove worktree using git
    if git worktree remove "$worktree_path" --force 2>/dev/null; then
        echo "Worktree removed successfully" >&2
        return 0
    fi

    # Fallback: manual cleanup
    echo "Attempting manual cleanup..." >&2
    rm -rf "$worktree_path" 2>/dev/null || true
    git worktree prune 2>/dev/null || true

    echo "Cleanup complete" >&2
}

# Create PR for release branch if it doesn't exist
create_release_pr() {
    local release_branch="$1"
    local source_branch="$2"
    local push_remote="$3"
    local pr_remote="$4"
    local version="$5"

    # Check if gh CLI is available
    if ! command -v gh &> /dev/null; then
        echo "⚠️  gh CLI not found - skipping PR creation"
        echo "Manual PR creation needed: $push_remote/$release_branch → $pr_remote/$source_branch"
        return 1
    fi

    # Check if PR already exists against PR remote
    if gh pr list --head "$release_branch" --base "$source_branch" --state open --json title --jq length | grep -q "^1$"; then
        echo "✅ PR already exists for $release_branch → $pr_remote/$source_branch"
        return 0
    fi

    # Create the PR against PR remote
    echo "Creating PR: $push_remote/$release_branch → $pr_remote/$source_branch"
    local pr_title="Release: Merge $release_branch to $source_branch"
    local pr_body="Automated release branch merge.

Version: $version
From: $push_remote/$release_branch
To: $pr_remote/$source_branch

Workflow:
1. Merge this PR in $pr_remote
2. Sync $pr_remote/$source_branch back to $push_remote/$source_branch

This PR was auto-generated by the deploy script."

    if gh pr create \
        --title "$pr_title" \
        --body "$pr_body" \
        --head "$release_branch" \
        --base "$source_branch" \
        --repo "$(git config --get remote.${pr_remote}.url)" 2>/dev/null; then
        echo "✅ PR created successfully: $release_branch → $pr_remote/$source_branch"
        return 0
    else
        echo "⚠️  Failed to create PR for $release_branch"
        echo "Manual PR creation needed: $push_remote/$release_branch → $pr_remote/$source_branch"
        return 1
    fi
}

# Parse flags
BRANCH_MODE="current"
TARGET_BRANCH=""
REMOTE="origin"
PR_REMOTE="upstream"
WORKTREE_PATH=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--branch)
            if [ -z "$2" ]; then
                echo "Error: -b flag requires a branch name"
                show_help
                exit 1
            fi
            BRANCH_MODE="worktree"
            TARGET_BRANCH="$2"
            shift 2
            ;;
        -r|--remote)
            if [ -z "$2" ]; then
                echo "Error: -r flag requires a remote name"
                show_help
                exit 1
            fi
            REMOTE="$2"
            shift 2
            ;;
        --pr-remote)
            if [ -z "$2" ]; then
                echo "Error: --pr-remote flag requires a remote name"
                show_help
                exit 1
            fi
            PR_REMOTE="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        major|minor|patch|stage|demo)
            VERSION_ARG="$1"
            shift
            break
            ;;
        *)
            echo "Error: Unknown option '$1'"
            show_help
            exit 1
            ;;
    esac
done

# No version argument provided
if [ -z "$VERSION_ARG" ]; then
    echo "Error: No version option provided."
    show_help
    exit 1
fi

# Determine current branch and deployment mode
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
IS_MASTER=0
CREATE_RELEASE_BRANCH=0
DEPLOY_BRANCH=""

if [ "$BRANCH_MODE" = "worktree" ]; then
    # Explicit branch provided via -b flag
    CREATE_RELEASE_BRANCH=1
    DEPLOY_BRANCH="$TARGET_BRANCH"
elif [ "$CURRENT_BRANCH" = "master" ] || [ "$CURRENT_BRANCH" = "main" ]; then
    # On master/main - create release branch
    CREATE_RELEASE_BRANCH=1
    DEPLOY_BRANCH="$CURRENT_BRANCH"
    IS_MASTER=1
else
    # On feature branch - deploy from current branch, require master merge
    echo "⚠️  Current branch: $CURRENT_BRANCH (not master)"
    echo
    echo "To deploy from a feature branch:"
    echo "  1. Master must be merged into current branch"
    echo "  2. Changes will be pushed to current branch (no release branch created)"
    echo

    # Check if master has been merged
    if ! git merge-base --is-ancestor origin/master HEAD 2>/dev/null; then
        echo "❌ Error: origin/master has not been merged into $CURRENT_BRANCH"
        echo
        echo "Please merge master first:"
        echo "  git fetch origin"
        echo "  git merge origin/master"
        exit 1
    fi

    echo "✅ Master is merged into current branch"
    echo "Deploying from: $CURRENT_BRANCH (version bump only, no release branch)"
    echo

    CREATE_RELEASE_BRANCH=0
    DEPLOY_BRANCH="$CURRENT_BRANCH"
fi

# Generate release information only if creating release branch
if [ $CREATE_RELEASE_BRANCH -eq 1 ]; then
    PETNAME=$(petname 2>/dev/null || echo "unknown")
    get_release_type() {
        case "$1" in
            major|minor|patch) echo "prod" ;;
            stage) echo "stage" ;;
            demo) echo "demo" ;;
            *) echo "" ;;
        esac
    }
    RELEASE_TYPE=$(get_release_type "$VERSION_ARG")
    RELEASE_BRANCH="release/${RELEASE_TYPE}_${PETNAME}"

    echo "Creating release branch: $RELEASE_BRANCH (petname: $PETNAME)"
    echo
else
    RELEASE_BRANCH=""
    echo "Deploying to current branch: $DEPLOY_BRANCH"
    echo
fi

# Worktree mode setup
if [ "$BRANCH_MODE" = "worktree" ]; then
    echo "=== Worktree Mode ==="
    validate_branch "$TARGET_BRANCH"

    WORKTREE_PATH=$(create_worktree "$TARGET_BRANCH")
    trap "cleanup_worktree '$WORKTREE_PATH'" EXIT INT TERM

    echo "Changing to worktree directory..."
    cd "$WORKTREE_PATH"
    echo "Current directory: $(pwd)"
    echo
fi

# Main deployment logic
case "$VERSION_ARG" in
    major|minor|patch)
        # Production deployment - bump stable version
        # If running from container/ directory, go to root
        if [ -d "../league_manager" ]; then
            cd ..
        fi

        # Read current version
        CURRENT_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
        echo "Current version: $CURRENT_VERSION"

        # Extract base version (remove any +demo.X or -rc.X suffix)
        BASE_VERSION="${CURRENT_VERSION%%+*}"
        BASE_VERSION="${BASE_VERSION%%-*}"

        echo "Base version: $BASE_VERSION"

        # Parse version components
        IFS='.' read -r MAJOR MINOR PATCH <<< "$BASE_VERSION"

        # Bump version based on argument
        case "$VERSION_ARG" in
            major)
                NEW_MAJOR=$((MAJOR + 1))
                NEW_VERSION="${NEW_MAJOR}.0.0"
                ;;
            minor)
                NEW_MINOR=$((MINOR + 1))
                NEW_VERSION="${MAJOR}.${NEW_MINOR}.0"
                ;;
            patch)
                NEW_PATCH=$((PATCH + 1))
                NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
                ;;
        esac

        echo "Creating version: $NEW_VERSION"

        # Update version files directly
        sed -i "s/__version__ = \".*\"/__version__ = \"$NEW_VERSION\"/" league_manager/__init__.py
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" liveticker/package.json
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" passcheck/package.json
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" scorecard/package.json
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" gameday_designer/package.json
        sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
        sed -i "s/current_version = \".*\"/current_version = \"$NEW_VERSION\"/" pyproject.toml

        # Regenerate uv.lock to match updated pyproject.toml
        echo "Regenerating uv.lock..."
        uv lock

        # Commit and tag
        git add league_manager/__init__.py liveticker/package.json passcheck/package.json scorecard/package.json gameday_designer/package.json pyproject.toml uv.lock
        git commit -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"

        # Push commits and tags
        if [ $CREATE_RELEASE_BRANCH -eq 1 ]; then
            if git push -u $REMOTE HEAD:refs/heads/$RELEASE_BRANCH && git push $REMOTE --tags; then
                # Create PR for release branch (to PR_REMOTE, not REMOTE)
                create_release_pr "$RELEASE_BRANCH" "$DEPLOY_BRANCH" "$REMOTE" "$PR_REMOTE" "$NEW_VERSION"
            fi
        else
            git push $REMOTE $DEPLOY_BRANCH && git push $REMOTE --tags
        fi

        # Show new version
        FINAL_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
        echo "✅ Production release deployed: $FINAL_VERSION"
        echo "Release branch: $RELEASE_BRANCH"
        ;;
    stage)
        # Staging deployment - create/increment RC version
        # If running from container/ directory, go to root
        if [ -d "../league_manager" ]; then
            cd ..
        fi

        # Read current version
        CURRENT_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
        echo "Current version: $CURRENT_VERSION"

        # Determine bump strategy
        if [[ $CURRENT_VERSION =~ -rc\.([0-9]+)$ ]]; then
            # Already on RC version - bump rc_build (e.g., 2.13.1-rc.1 → 2.13.1-rc.2)
            echo "Incrementing RC build number..."
            RC_NUM="${BASH_REMATCH[1]}"
            NEW_RC=$((RC_NUM + 1))
            BASE_VERSION="${CURRENT_VERSION%-rc.*}"
            NEW_VERSION="${BASE_VERSION}-rc.${NEW_RC}"

            echo "Creating version: $NEW_VERSION"

            sed -i "s/__version__ = \".*\"/__version__ = \"$NEW_VERSION\"/" league_manager/__init__.py
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" liveticker/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" passcheck/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" scorecard/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" gameday_designer/package.json
            sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
            sed -i "s/current_version = \".*\"/current_version = \"$NEW_VERSION\"/" pyproject.toml

            echo "Regenerating uv.lock..."
            uv lock

            git add league_manager/__init__.py liveticker/package.json passcheck/package.json scorecard/package.json gameday_designer/package.json pyproject.toml uv.lock
            git commit -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
            git tag -a "v$NEW_VERSION" -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
        else
            # Stable version - bump patch and create RC.1 (e.g., 2.13.0 → 2.13.1-rc.1)
            # Manual approach needed because bump-my-version cannot create RC from stable
            echo "Bumping patch version and creating RC.1..."
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}-rc.1"

            echo "Creating version: $NEW_VERSION"

            # Update version files directly
            sed -i "s/__version__ = \".*\"/__version__ = \"$NEW_VERSION\"/" league_manager/__init__.py
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" liveticker/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" passcheck/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" scorecard/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" gameday_designer/package.json
            sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
            sed -i "s/current_version = \".*\"/current_version = \"$NEW_VERSION\"/" pyproject.toml

            # Regenerate uv.lock to match updated pyproject.toml
            echo "Regenerating uv.lock..."
            uv lock

            # Commit and tag
            git add league_manager/__init__.py liveticker/package.json passcheck/package.json scorecard/package.json gameday_designer/package.json pyproject.toml uv.lock
            git commit -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
            git tag -a "v$NEW_VERSION" -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
        fi

        # Push commits and tags
        if [ "$CREATE_RELEASE_BRANCH" -eq 1 ]; then
            if git push -u $REMOTE HEAD:refs/heads/$RELEASE_BRANCH && git push $REMOTE --tags; then
                # Create PR for release branch (to PR_REMOTE, not REMOTE)
                NEW_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
                create_release_pr "$RELEASE_BRANCH" "$DEPLOY_BRANCH" "$REMOTE" "$PR_REMOTE" "$NEW_VERSION"
            fi
        else
            git push $REMOTE $DEPLOY_BRANCH && git push $REMOTE --tags
        fi

        # Show new version
        NEW_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
        echo "✅ Staging deployment triggered: $NEW_VERSION"
        if [ $CREATE_RELEASE_BRANCH -eq 1 ]; then
            echo "Release branch: $RELEASE_BRANCH"
            echo "PR target: $PR_REMOTE/$DEPLOY_BRANCH"
        else
            echo "Deployed to: $DEPLOY_BRANCH"
        fi
        ;;
    demo)
        # Demo deployment - create/increment demo version
        # If running from container/ directory, go to root
        if [ -d "../league_manager" ]; then
            cd ..
        fi

        # Read current version
        CURRENT_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
        echo "Current version: $CURRENT_VERSION"

        # Determine bump strategy
        if [[ $CURRENT_VERSION =~ \+demo\.([0-9]+)$ ]]; then
            # Already on demo version - bump demo_build (e.g., 3.11.3+demo.1 → 3.11.3+demo.2)
            echo "Incrementing demo build number..."
            DEMO_NUM="${BASH_REMATCH[1]}"
            NEW_DEMO=$((DEMO_NUM + 1))
            BASE_VERSION="${CURRENT_VERSION%+demo.*}"
            NEW_VERSION="${BASE_VERSION}+demo.${NEW_DEMO}"

            echo "Creating version: $NEW_VERSION"

            sed -i "s/__version__ = \".*\"/__version__ = \"$NEW_VERSION\"/" league_manager/__init__.py
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" liveticker/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" passcheck/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" scorecard/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" gameday_designer/package.json
            sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
            sed -i "s/current_version = \".*\"/current_version = \"$NEW_VERSION\"/" pyproject.toml

            echo "Regenerating uv.lock..."
            uv lock

            git add league_manager/__init__.py liveticker/package.json passcheck/package.json scorecard/package.json gameday_designer/package.json pyproject.toml uv.lock
            git commit -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
            git tag -af "v$NEW_VERSION" -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
        else
            # Non-demo version - create demo.1 (e.g., 3.11.3 → 3.11.3+demo.1)
            echo "Creating initial demo version..."
            NEW_VERSION="${CURRENT_VERSION}+demo.1"

            echo "Creating version: $NEW_VERSION"

            # Update version files directly
            sed -i "s/__version__ = \".*\"/__version__ = \"$NEW_VERSION\"/" league_manager/__init__.py
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" liveticker/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" passcheck/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" scorecard/package.json
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" gameday_designer/package.json
            sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
            sed -i "s/current_version = \".*\"/current_version = \"$NEW_VERSION\"/" pyproject.toml

            # Regenerate uv.lock to match updated pyproject.toml
            echo "Regenerating uv.lock..."
            uv lock

            # Commit and tag
            git add league_manager/__init__.py liveticker/package.json passcheck/package.json scorecard/package.json gameday_designer/package.json pyproject.toml uv.lock
            git commit -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
            git tag -af "v$NEW_VERSION" -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
        fi

        # Push commits and tags
        if [ "$CREATE_RELEASE_BRANCH" -eq 1 ]; then
            if git push -u $REMOTE HEAD:refs/heads/$RELEASE_BRANCH && git push $REMOTE --tags; then
                # Create PR for release branch (to PR_REMOTE, not REMOTE)
                NEW_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
                create_release_pr "$RELEASE_BRANCH" "$DEPLOY_BRANCH" "$REMOTE" "$PR_REMOTE" "$NEW_VERSION"
            fi
        else
            git push $REMOTE $DEPLOY_BRANCH && git push $REMOTE --tags
        fi

        # Show new version
        NEW_VERSION=$(grep "__version__" league_manager/__init__.py | cut -d'"' -f2)
        echo "✅ Demo deployment triggered: $NEW_VERSION"
        if [ $CREATE_RELEASE_BRANCH -eq 1 ]; then
            echo "Release branch: $RELEASE_BRANCH"
            echo "PR target: $PR_REMOTE/$DEPLOY_BRANCH"
        else
            echo "Deployed to: $DEPLOY_BRANCH"
        fi
        ;;
    *)
        echo "Error: Invalid option '$VERSION_ARG'"
        show_help
        exit 1
        ;;
esac
