FROM python:3.11-slim AS builder
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ARG APP_DIR="/app"

WORKDIR ${APP_DIR}

# install environment
COPY ./requirements.txt ${APP_DIR}
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# collect static files
python manage.py collectstatic --no-input --clear

FROM nginx:stable

COPY --from=init /app/league_manager/league_manager/static /static
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
