# Generated by Django 5.0.4 on 2024-10-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamedays', '0021_gameday_address'),
        ('officials', '0013_officialposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('team_option', models.CharField(choices=[('home', 'Home Team'), ('away', 'Away Team'), ('none', 'None')], default='none', help_text='Shall there be a team name displayed?', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardCategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='scorecard2.scorecardcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GameSetupCategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard2.scorecardcategory')),
                ('category_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard2.scorecardcategoryvalue')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leagues', models.ManyToManyField(related_name='scorecard_config_for_leagues', to='gamedays.league')),
            ],
        ),
        migrations.AddField(
            model_name='scorecardcategory',
            name='scorecard_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard2.scorecardconfig'),
        ),
        migrations.CreateModel(
            name='ScorecardGameSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeCaptain', models.CharField(blank=True, max_length=100)),
                ('awayCaptain', models.CharField(blank=True, max_length=100)),
                ('hasFinalScoreChanged', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('category_values', models.ManyToManyField(through='scorecard2.GameSetupCategoryValue', to='scorecard2.scorecardcategory')),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_gamesetup', to='gamedays.gameinfo')),
            ],
        ),
        migrations.AddField(
            model_name='gamesetupcategoryvalue',
            name='game_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_setup_category_values', to='scorecard2.scorecardgamesetup'),
        ),
        migrations.CreateModel(
            name='ScorecardOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False)),
                ('official_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.officialposition')),
                ('scorecard_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard2.scorecardconfig')),
            ],
        ),
    ]
