# Generated by Django 5.0.4 on 2024-10-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0013_officialposition'),
        ('scorecard2', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardofficial',
            name='position_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scorecardofficial',
            name='official_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.officialposition'),
        ),
    ]
