# Generated by Django 4.1.7 on 2023-11-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamedays', '0017_team_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playerlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('trikotnumber', models.IntegerField()),
                ('passnumber', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('gamedays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gamedays.gameday')),
            ],
        ),
    ]
