# Generated by Django 4.2.10 on 2024-02-09 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gamedays", "0019_gameofficial_gamedays_ga_gameinf_d5ecbf_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playerlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("jersey_number", models.IntegerField()),
                ("pass_number", models.IntegerField()),
                (
                    "sex",
                    models.IntegerField(choices=[(1, "Weiblich"), (2, "Männlich")]),
                ),
                ("year_of_birth", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TeamRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_teams",
                    models.ManyToManyField(
                        related_name="relationship_additional_teams", to="gamedays.team"
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedays.league",
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_team",
                        to="gamedays.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerlistGameday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameday_jersey", models.IntegerField()),
                (
                    "gameday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedays.gameday",
                    ),
                ),
                (
                    "playerlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passcheck.playerlist",
                    ),
                ),
            ],
            options={
                "db_table": "passcheck_playerlist_gamedays",
            },
        ),
        migrations.AddField(
            model_name="playerlist",
            name="gamedays",
            field=models.ManyToManyField(
                through="passcheck.PlayerlistGameday", to="gamedays.gameday"
            ),
        ),
        migrations.AddField(
            model_name="playerlist",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="gamedays.team"
            ),
        ),
        migrations.CreateModel(
            name="PasscheckVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("official_name", models.CharField(max_length=100)),
                (
                    "gameday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedays.gameday",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gamedays.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EligibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_gamedays", models.IntegerField()),
                (
                    "max_subs_in_other_leagues",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("minimum_player_strength", models.IntegerField()),
                (
                    "maximum_player_strength",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("is_relegation_allowed", models.BooleanField(default=False)),
                ("min_gamedays_for_final", models.IntegerField(default=2)),
                ("ignore_player_age_until", models.IntegerField(default=19)),
                ("except_for_women", models.BooleanField(default=True)),
                (
                    "eligible_in",
                    models.ManyToManyField(
                        related_name="eligible_in", to="gamedays.league"
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_for",
                        to="gamedays.league",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="playerlistgameday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gameday_jersey__gte", 0), ("gameday_jersey__lte", 99)
                ),
                name="gameday_jersey_number_btw_0_and_99",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerlist",
            constraint=models.UniqueConstraint(
                fields=("team", "jersey_number"), name="unique_team_jersey_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerlist",
            constraint=models.UniqueConstraint(
                fields=("team", "pass_number"), name="unique_team_pass_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerlist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("jersey_number__gte", 0), ("jersey_number__lte", 99)
                ),
                name="jersey_number_btw_0_and_99",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "maximum_player_strength__gte",
                        models.F("minimum_player_strength"),
                    )
                ),
                name="maximum_player_strength_must_be_greater_equal_minimum",
            ),
        ),
    ]
