# Generated by Django 4.1.7 on 2023-11-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0017_team_association'),
        ('passcheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerlist',
            name='gamedays',
        ),
        migrations.AddField(
            model_name='playerlist',
            name='gamedays',
            field=models.ManyToManyField(to='gamedays.gameday'),
        ),
    ]
