# Generated by Django 4.2.10 on 2024-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcheckverification',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
