# Generated by Django 4.1.7 on 2023-11-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0017_team_association'),
        ('passcheck', '0002_remove_playerlist_gamedays_playerlist_gamedays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerlist',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='playerlist',
            name='playerid',
        ),
        migrations.AddField(
            model_name='playerlist',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gamedays.team'),
            preserve_default=False,
        ),
    ]
