# Generated by Django 4.1.7 on 2024-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0003_rename_name_playerlist_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Weiblich'), (2, 'Männlich')]),
        ),

    ]
