# Generated by Django 5.0.4 on 2024-11-10 09:18

from django.db import migrations


def migrate_player_data(apps, schema_editor):
    Playerlist = apps.get_model('passcheck', 'Playerlist')
    Person = apps.get_model('gamedays', 'Person')
    Player = apps.get_model('passcheck', 'Player')

    for playerlist in Playerlist.objects.all():
        person = Person.objects.create(
            first_name=playerlist.first_name,
            last_name=playerlist.last_name,
            sex=playerlist.sex,
            year_of_birth=playerlist.year_of_birth,
        )

        player = Player.objects.create(
            person=person,
            pass_number=playerlist.pass_number,
        )

        playerlist.player_id = player.id
        playerlist.joined_on = '2024-04-01'
        playerlist.save()


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0004_playerlist_joined_on_playerlist_left_on_player_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_player_data),
    ]
