# Generated by Django 4.1.7 on 2024-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0005_rename_firstname_playerlist_first_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playerlist',
            constraint=models.UniqueConstraint(fields=('team', 'jersey_number'), name='unique_team_jersey_number'),
        ),
        migrations.AddConstraint(
            model_name='playerlist',
            constraint=models.UniqueConstraint(fields=('team', 'pass_number'), name='unique_team_pass_number'),
        ),
    ]
