# Generated by Django 4.1.7 on 2024-01-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0009_playerlist_year_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='min_gamedays_for_final',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='ignore_player_age_unitl',
            field=models.IntegerField(default=19),
        ),
    ]
