# Generated by Django 4.1.7 on 2024-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0012_playerlistgameday_gameday_jersery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerlistgameday',
            old_name='gameday_jersery',
            new_name='gameday_jersey',
        ),
        migrations.AddConstraint(
            model_name='playerlistgameday',
            constraint=models.CheckConstraint(check=models.Q(('gameday_jersey__gte', 0), ('gameday_jersey__lte', 99)),
                                              name='gameday_jersey_number_btw_0_and_99'),
        ),
    ]
