# Generated by Django 4.1.7 on 2024-01-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0019_gameofficial_gamedays_ga_gameinf_d5ecbf_idx'),
        ('passcheck', '0013_rename_gameday_jersery_playerlistgameday_gameday_jersey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_teams', models.ManyToManyField(related_name='additional_teams', to='gamedays.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedays.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team',
                                           to='gamedays.team')),
            ],
        ),
    ]
