# Generated by Django 4.1.7 on 2024-02-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0019_gameofficial_gamedays_ga_gameinf_d5ecbf_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passcheck', '0014_teamrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrelationship',
            name='additional_teams',
            field=models.ManyToManyField(related_name='relationship_additional_teams', to='gamedays.team'),
        ),
        migrations.AlterField(
            model_name='teamrelationship',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_team',
                                       to='gamedays.team'),
        ),
        migrations.CreateModel(
            name='PasscheckVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_name', models.CharField(max_length=100)),
                ('gameday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedays.gameday')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedays.team')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
