# Generated by Django 4.1.7 on 2024-02-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0015_alter_teamrelationship_additional_teams_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibilityrule',
            old_name='ignore_player_age_unitl',
            new_name='ignore_player_age_until',
        ),
        migrations.RenameField(
            model_name='eligibilityrule',
            old_name='max_players',
            new_name='max_subs_in_other_leagues',
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='maximum_player_strength',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='minimum_player_strength',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
