# Generated by Django 4.1.7 on 2024-02-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('passcheck', '0016_rename_ignore_player_age_unitl_eligibilityrule_ignore_player_age_until_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eligibilityrule',
            constraint=models.CheckConstraint(
                check=models.Q(('maximum_player_strength__gte', models.F('minimum_player_strength'))),
                name='maximum_player_strength_must_be_greater_equal_minimum'),
        ),
    ]
