name: ${SERVICE_NAME}
services:
  mysql:
    image: mariadb:latest
    container_name: ${COMPOSE_PROJECT_NAME}.mysql
    restart: unless-stopped
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./mysql-data:/var/lib/mysql"
      - "./mysql-init:/docker-entrypoint-initdb.d:ro"
    env_file: ls.env.demo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "sh", "-c", "mariadb -h localhost --skip-ssl -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
      interval: 15s
      timeout: 5s
      retries: 15
      start_period: 90s
    labels:
      - traefik.enable=false
      # portainer team
      - io.portainer.accesscontrol.teams=leaguesphere

  www:
    image: leaguesphere/frontend:demo
    container_name: ${COMPOSE_PROJECT_NAME}.www
    volumes:
      - "../container/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "../container/healthcheck.demo.sh:/healthcheck.sh"
    labels:
      # HTTP -> HTTPS redirect
      - traefik.http.routers.${SERVICE_NAME}-http.entrypoints=web
      - traefik.http.routers.${SERVICE_NAME}-http.rule=Host(`demo.leaguesphere.app`)
      - traefik.http.routers.${SERVICE_NAME}-http.middlewares=${SERVICE_NAME}-https
      - traefik.http.middlewares.${SERVICE_NAME}-https.redirectscheme.scheme=https

      # HTTPS for lehel.xyz (DNS resolver)
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_HOST}`)
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencryptdnsresolver

      # HTTPS for leaguesphere.app (HTTP resolver)
      - traefik.http.routers.${SERVICE_NAME}_prod.tls=true
      - traefik.http.routers.${SERVICE_NAME}_prod.rule=Host(`demo.leaguesphere.app`)
      - traefik.http.routers.${SERVICE_NAME}_prod.tls.certresolver=letsencrypthttpresolver

      # Local resolution (HTTP)
      - traefik.http.routers.${SERVICE_NAME}_local_qualified.rule=Host(`${SERVICE_NAME}.${LOCAL_HOSTNAME}`)
      - traefik.http.routers.${SERVICE_NAME}_local_qualified.entrypoints=web

      # Portainer team
      - io.portainer.accesscontrol.teams=leaguesphere

      # Watchtower scope
      - com.centurylinklabs.watchtower.scope=dev
    networks:
      - backend
      - proxy
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  backend:
    image: leaguesphere/backend:demo
    container_name: ${COMPOSE_PROJECT_NAME}.backend
    command: gunicorn -b 0.0.0.0:8000 league_manager.wsgi
    healthcheck:
      test: ["CMD-SHELL", "curl -A healthcheck -H \"Accept: application/json\" http://localhost:8000/health/?format=json"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 120s
    labels:
      - traefik.enable=false
      # portainer team
      - io.portainer.accesscontrol.teams=leaguesphere
      # Watchtower scope
      - com.centurylinklabs.watchtower.scope=dev
    env_file: ls.env.demo
    environment:
      DJANGO_SETTINGS_MODULE: league_manager.settings.demo
      RUN_MIGRATIONS: true
    networks:
      - backend
      - egress
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

networks:
  backend:
    internal: true
  egress:
    internal: false
  proxy:
    external: true
