# Generated by Django 6.0.3 on 2026-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_pages",
                    models.JSONField(
                        default=list,
                        help_text='List of regex strings, e.g., ["^/api/.*", "^/dashboard/.*"]',
                    ),
                ),
            ],
        ),
    ]
