# Generated by Django 6.0.3 on 2026-04-10 12:22

from django.db import migrations


def create_default_config(apps, schema_editor):
    SiteConfiguration = apps.get_model("league_manager", "SiteConfiguration")

    MAINTENANCE_PAGES = [
        "/gamedays/gameday/new/",
        "/passcheck/player/create",
        "^/passcheck/player/\d+/(update|delete|transfer)/$",
        "/officials/gameday/sign-up",
        "/gamedays/gameday/design",
        "^/gamedays/gameday/\d+/gameinfos/(update|delete)/$",
        "^/gamedays/gameday/\d+/(update|delete)/$",
    ]
    SiteConfiguration.objects.get_or_create(
        id=1,
        defaults={"maintenance_mode": False, "maintenance_pages": MAINTENANCE_PAGES},
    )


def remove_default_config(apps, schema_editor):
    SiteConfiguration = apps.get_model("league_manager", "SiteConfiguration")
    SiteConfiguration.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("league_manager", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_config, remove_default_config),
    ]
