# Generated by Django 6.0.7 on 2026-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0003_add_maintenance_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='maintenance_pages',
            field=models.JSONField(default=list, help_text='List of regex strings (only used when scope is "Custom"), e.g., ["^/api/.*", "^/dashboard/.*"]'),
        ),
    ]
