# Generated by Django 3.1.2 on 2020-11-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Beschreibung', models.CharField(max_length=20)),
                ('Ort', models.CharField(max_length=20)),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammanager.division')),
            ],
        ),
    ]
