# Generated by Django 3.1.2 on 2020-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='Region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Ort',
            new_name='place',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo'),
        ),
    ]
