# Generated by Django 3.1.5 on 2021-03-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0005_auto_20210320_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlog',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teammanager.team'),
        ),
    ]
