# Generated by Django 3.2.4 on 2021-09-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0007_gameinfo_in_possession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]