# Generated by Django 3.2.9 on 2021-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0010_auto_20211112_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='status',
            field=models.CharField(default='scheduled', max_length=100),
        ),
    ]