# Generated by Django 4.1 on 2023-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0012_alter_gameinfo_options_alter_team_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
