# Generated by Django 5.2.8 on 2026-02-27 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0001_initial"),
        ("gamedays", "0023_gameinfo_league_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialsAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=None, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accesscontrol.association",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(on_delete=models.SET(213), to="accesscontrol.team"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["id", "team"], name="accesscontr_id_9d6afe_idx"
                    ),
                    models.Index(
                        fields=["id", "association"], name="accesscontr_id_ab708b_idx"
                    ),
                ],
            },
        ),
    ]
