# Generated by Django 5.2.8 on 2026-02-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0002_officialsassignment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfficialsAssignment",
        ),
    ]
