# Generated by Django 5.2.8 on 2026-03-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0003_delete_officialsassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbr", models.CharField(max_length=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INTERNATIONAL", "International Federation"),
                            ("NATIONAL", "National Federation"),
                            ("REGIONAL", "Regional Association"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accesscontrol.association",
                    ),
                ),
            ],
        ),
    ]
