# Generated by Django 5.2.8 on 2026-03-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0004_association"),
        ("gamedays", "0028_remove_league_association"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueAssociationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accesscontrol.association",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedays.league",
                    ),
                ),
            ],
        ),
    ]
