# Generated by Django 3.2.9 on 2021-11-12 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officiallicensehistory',
            old_name='offical',
            new_name='official',
        ),
    ]
