# Generated by Django 4.1 on 2022-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officials", "0004_officialexternalgames"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialexternalgames",
            name="comment",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
