# Generated by Django 4.1 on 2023-03-30 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0013_association"),
        ("officials", "0006_officiallicensehistory_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="official",
            name="association",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gamedays.association",
            ),
        ),
    ]
