# Generated by Django 4.1.7 on 2023-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('officials', '0007_official_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialexternalgames',
            name='halftime_duration',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialexternalgames',
            name='has_clockcontrol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officialexternalgames',
            name='notification_date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialexternalgames',
            name='reporter_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='officialexternalgames',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
