# Generated by Django 5.0.4 on 2024-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0012_rename_officialgamessignup_officialgamedaysignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_position_counted_as_entry', models.BooleanField(default=True)),
            ],
        ),
    ]
