# Generated by Django 5.2.8 on 2026-03-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0024_person_user"),
        ("officials", "0015_alter_official_association_alter_official_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="official",
            name="association",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accesscontrol.association",
            ),
        ),
    ]
