# Generated by Django 5.2.8 on 2026-03-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0004_association"),
        ("officials", "0016_alter_official_association"),
    ]

    operations = [
        migrations.AlterField(
            model_name="official",
            name="association",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accesscontrol.association",
            ),
        ),
    ]
