# Generated by Django 3.1.5 on 2021-03-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0002_auto_20210308_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameday',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamedays.league'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameday',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamedays.season'),
            preserve_default=False,
        ),
    ]
