# Generated by Django 3.0.8 on 2020-07-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.TimeField()),
                ('field', models.PositiveSmallIntegerField()),
                ('officials', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('pin', models.PositiveSmallIntegerField(null=True)),
                ('gameStarted', models.TimeField(null=True)),
                ('gameHalftime', models.TimeField(null=True)),
                ('gameFinished', models.TimeField(null=True)),
                ('stage', models.CharField(max_length=100)),
                ('standing', models.CharField(max_length=100)),
                ('gameday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedays.Gameday')),
            ],
        ),
        migrations.CreateModel(
            name='Gameresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('fh', models.SmallIntegerField(null=True)),
                ('sh', models.SmallIntegerField(null=True)),
                ('pa', models.PositiveSmallIntegerField(null=True)),
                ('isHome', models.BooleanField(default=False)),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedays.Gameinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
