# Generated by Django 3.1.1 on 2020-09-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0003_auto_20200730_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='officials',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
