# Generated by Django 3.1.2 on 2020-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0004_auto_20200917_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameday',
            name='format',
            field=models.CharField(blank=True, default='62', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='gameFinished',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='gameHalftime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='gameStarted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='pin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
