# Generated by Django 3.1.5 on 2021-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0004_auto_20210316_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlog',
            name='input',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='status',
            field=models.CharField(default='Geplant', max_length=100),
        ),
    ]
