# Generated by Django 3.1.5 on 2021-03-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0005_auto_20210320_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamlog",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gamedays.team",
            ),
        ),
    ]
