# Generated by Django 3.1.2 on 2020-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0005_auto_20201009_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='format',
            field=models.CharField(blank=True, default='6_2', max_length=100),
        ),
    ]
