# Generated by Django 3.1.7 on 2021-04-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0006_auto_20210322_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='in_possession',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
