# Generated by Django 3.1.5 on 2021-02-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0007_gameofficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('sixPoints', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('twoPoints', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('onePoint', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cop', models.BooleanField(default=False)),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedays.gameinfo')),
            ],
        ),
    ]
