# Generated by Django 3.1.5 on 2021-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0008_teamlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamlog',
            old_name='number',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='teamlog',
            name='onePoint',
        ),
        migrations.RemoveField(
            model_name='teamlog',
            name='sixPoints',
        ),
        migrations.RemoveField(
            model_name='teamlog',
            name='twoPoints',
        ),
        migrations.AddField(
            model_name='teamlog',
            name='event',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamlog',
            name='half',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamlog',
            name='player',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamlog',
            name='team',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamlog',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
