# Generated by Django 3.2.9 on 2021-11-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0009_auto_20211105_1341"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameofficial",
            old_name="offical",
            new_name="official",
        ),
        migrations.AlterField(
            model_name="gameofficial",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
