# Generated by Django 3.1.5 on 2021-02-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0009_auto_20210207_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctResult', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('fhPossession', models.CharField(max_length=100)),
                ('homeCaptain', models.CharField(blank=True, max_length=100)),
                ('awayCaptain', models.CharField(blank=True, max_length=100)),
                ('hasFinalScoreChanged', models.BooleanField(default=False)),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedays.gameinfo')),
            ],
        ),
    ]
