# Generated by Django 4.1 on 2023-02-24 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0010_auto_20211112_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameday',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='gameinfo',
            options={'ordering': ['scheduled']},
        ),
    ]
