# Generated by Django 3.1.5 on 2021-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0010_gamesetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlog',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
