# Generated by Django 4.1 on 2023-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0011_alter_gameday_options_alter_gameinfo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameinfo",
            options={},
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.CharField(max_length=1000, unique=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
