# Generated by Django 4.1.7 on 2023-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0015_alter_achievement_id_alter_association_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
