# Generated by Django 4.1.7 on 2023-04-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0016_alter_team_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="association",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="gamedays.association",
            ),
        ),
    ]
