# Generated by Django 4.1.7 on 2024-01-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamedays', '0018_gameday_gamedays_ga_id_167c15_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gameofficial',
            index=models.Index(fields=['gameinfo', 'position'], name='gamedays_ga_gameinf_d5ecbf_idx'),
        ),
    ]
