# Generated by Django 4.2.9 on 2024-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0020_gamesetup_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameday",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
    ]
