# Generated by Django 5.0.4 on 2024-10-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0021_gameday_address'),
        ('officials', '0013_officialposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameofficial',
            name='official_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.officialposition'),
        ),
    ]
