# Generated by Django 5.2.7 on 2026-01-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0023_gameinfo_league_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameday",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameday",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gameinfo",
            name="final_score",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameinfo",
            name="halftime_score",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameinfo",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
