# Generated by Django 5.2.4 on 2025-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0023_gameinfo_league_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]