# Generated by Django 5.2.4 on 2025-11-12 15:55

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    League = apps.get_model("gamedays", "League")
    Season = apps.get_model("gamedays", "Season")

    for league in League.objects.all():
        league.slug = slugify(league.name)
        league.save(update_fields=["slug"])

    for season in Season.objects.all():
        season.slug = slugify(season.name)
        season.save(update_fields=["slug"])

class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0024_league_slug_season_slug_alter_league_name_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
