# Generated by Django 5.2.7 on 2026-01-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0024_gameday_published_at_gameday_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameday",
            name="designer_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
