# Generated by Django 5.2.8 on 2026-03-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0004_association"),
        ("gamedays", "0024_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="association",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accesscontrol.association",
            ),
        ),
    ]
