# Generated by Django 5.2.7 on 2025-11-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0025_migrate_teammanager_permissions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gamedaymanager",
            new_name="gamedays_ga_user_id_a20da1_idx",
            old_name="gamedays_ga_user_id_1a2b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="gamedaymanager",
            new_name="gamedays_ga_gameday_1b493c_idx",
            old_name="gamedays_ga_gameday_4d5e6f_idx",
        ),
        migrations.RenameIndex(
            model_name="leaguemanager",
            new_name="gamedays_le_user_id_a9e4f5_idx",
            old_name="gamedays_le_user_id_70fa60_idx",
        ),
        migrations.RenameIndex(
            model_name="leaguemanager",
            new_name="gamedays_le_league__2a5f90_idx",
            old_name="gamedays_le_league__2c7b25_idx",
        ),
        migrations.RenameIndex(
            model_name="teammanager",
            new_name="gamedays_te_user_id_4469da_idx",
            old_name="gamedays_te_user_id_7g8h9i_idx",
        ),
        migrations.RenameIndex(
            model_name="teammanager",
            new_name="gamedays_te_team_id_dd5786_idx",
            old_name="gamedays_te_team_id_0j1k2l_idx",
        ),
    ]
