# Generated by Django 5.2.4 on 2025-11-12 15:55
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("gamedays", "0025_populate_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, blank=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, blank=True),
        ),
    ]
