# Generated by Django 5.2.7 on 2026-01-19 23:28

from django.db import migrations

def set_existing_gamedays_published(apps, schema_editor):
    Gameday = apps.get_model('gamedays', 'Gameday')
    # Update all existing gamedays to PUBLISHED
    Gameday.objects.all().update(status='PUBLISHED')

def reverse_set_existing_gamedays_published(apps, schema_editor):
    Gameday = apps.get_model('gamedays', 'Gameday')
    # Revert all gamedays to DRAFT (if needed for rollback)
    Gameday.objects.all().update(status='DRAFT')

class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0025_gameday_designer_data"),
    ]

    operations = [
        migrations.RunPython(set_existing_gamedays_published, reverse_set_existing_gamedays_published),
    ]
