# Generated by Django 5.2.8 on 2026-03-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0025_alter_team_association"),
        ("officials", "0017_alter_official_association"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Association",
        ),
    ]
