# Generated by Django 5.2.4 on 2025-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0026_make_slugs_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="season",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
