# Generated by Django 6.0.1 on 2026-02-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0026_set_existing_gamedays_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameresult",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gamedays.team",
            ),
        ),
    ]
