# Generated by Django 5.2.8 on 2026-03-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0004_association"),
        ("gamedays", "0026_delete_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accesscontrol.association",
            ),
        ),
    ]
