# Generated by Django 5.2.8 on 2026-03-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0027_league_association"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="association",
        ),
    ]
