# Generated by Django 5.2.4 on 2025-12-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0027_alter_league_name_alter_season_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seasonleagueteam",
            name="team",
        ),
        migrations.AddField(
            model_name="seasonleagueteam",
            name="teams",
            field=models.ManyToManyField(to="gamedays.team"),
        ),
    ]
