# Generated by Django 5.2.4 on 2025-10-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('gamedays', '0023_gameinfo_league_group')]

    dependencies = [
        ('league_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="gameinfo",
            name="league_group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_table.leaguegroup",
            ),
        ),
    ]
