# Generated by Django 6.0.2 on 2026-02-19 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0028_remove_gameinfo_redundant_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GamedayDesignerState",
            fields=[
                (
                    "gameday",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="designer_state",
                        serialize=False,
                        to="gamedays.gameday",
                    ),
                ),
                (
                    "state_data",
                    models.JSONField(
                        default=dict,
                        help_text="React Flow designer state (nodes, edges, teams)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gamedays_designer_state",
            },
        ),
    ]
