# Generated by Django 6.0.2 on 2026-02-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0029_gamedaydesignerstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameday",
            name="designer_data",
        ),
    ]
