# Generated by Django 6.0.3 on 2026-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0032_merge_20260320_2118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
