# Generated by Django 6.0.7 on 2026-08-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0039_alter_resourceurl_gameday_resourceurl_tournament_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameinfo",
            name="stage_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("preliminary", "Preliminary"),
                    ("final", "Final"),
                    ("placement", "Placement"),
                    ("custom", "Custom"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
