# Generated by Django 6.0 on 2025-12-14 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gamedays", "0023_gameinfo_league_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("num_teams", models.PositiveIntegerField()),
                ("num_fields", models.PositiveIntegerField()),
                ("num_groups", models.PositiveIntegerField(default=1)),
                ("game_duration", models.PositiveIntegerField(default=70)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "association",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_templates",
                        to="gamedays.association",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("team_mapping", models.JSONField()),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gameday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_applications",
                        to="gamedays.gameday",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="gameday_designer.scheduletemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.PositiveIntegerField()),
                ("slot_order", models.PositiveIntegerField()),
                ("stage", models.CharField(max_length=50)),
                ("standing", models.CharField(max_length=100)),
                ("home_group", models.PositiveIntegerField(blank=True, null=True)),
                ("home_team", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "home_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("away_group", models.PositiveIntegerField(blank=True, null=True)),
                ("away_team", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "away_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("official_group", models.PositiveIntegerField(blank=True, null=True)),
                ("official_team", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "official_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("break_after", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="gameday_designer.scheduletemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["field", "slot_order"],
            },
        ),
        migrations.CreateModel(
            name="TemplateUpdateRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_finished", models.CharField(max_length=100)),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_rule",
                        to="gameday_designer.templateslot",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_rules",
                        to="gameday_designer.scheduletemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateUpdateRuleTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("home", "Home Team"),
                            ("away", "Away Team"),
                            ("official", "Officials"),
                        ],
                        max_length=10,
                    ),
                ),
                ("standing", models.CharField(max_length=100)),
                ("place", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pre_finished_override",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "update_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_rules",
                        to="gameday_designer.templateupdaterule",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="scheduletemplate",
            index=models.Index(
                fields=["association", "name"], name="gameday_des_associa_0c1456_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduletemplate",
            index=models.Index(
                fields=["created_at"], name="gameday_des_created_f0dd38_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "association"),
                name="unique_template_name_per_association",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("num_teams__gt", 0)), name="positive_num_teams"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("num_fields__gt", 0)), name="positive_num_fields"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("game_duration__gte", 30), ("game_duration__lte", 120)
                ),
                name="valid_game_duration",
            ),
        ),
        migrations.AddIndex(
            model_name="templateslot",
            index=models.Index(
                fields=["template", "field", "slot_order"],
                name="gameday_des_templat_202a5c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="templateslot",
            index=models.Index(
                fields=["template", "stage"], name="gameday_des_templat_797ca1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templateupdaterule",
            unique_together={("slot",)},
        ),
        migrations.AlterUniqueTogether(
            name="templateupdateruleteam",
            unique_together={("update_rule", "role")},
        ),
    ]
