# Generated by Django 5.2.9 on 2026-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameday_designer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateslot",
            name="stage_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard Stage"), ("RANKING", "Ranking Stage")],
                default="STANDARD",
                max_length=20,
            ),
        ),
    ]
